[package]
name = "pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
demo = { path = "../demo" }
cs2 = { path = "../cs2" }
highlights = { path = "../highlights" }
director = { path = "../director" }
renderer = { path = "../renderer" }
faceit = { path = "../faceit" }
positions = { path = "../positions" }
geometry = { path = "../geometry" }
